### ISSUE TITLE
Expose certain stress _ variables

### ISSUE THREAD

**Issue by arijitlaik** [underworldcode/UWGeodynamics#29]
Exposing certain _variables would help out a lot, especially w.r.t stresses, i.e yield stress function (evaluating it over some passive markers in creating a profile etc, for example), and providing methods for fetching/getting shear and normal stresses on the swarm and or the mesh.

**Comment by arijitlaik** [comment]
@rbeucher  is there a simple way by which i can access the yield stress(one defined in the plasticity from rheology) along a passive marker??

**Comment by rbeucher** [comment]
It is not  exposed. We need to expose it from the viscosityFn function. Or better, build a cleaner function that return a field of the yieldStress... I have not done that yet because I was not sure how to deal with viscous-only material... That viscoisityFn function needs to be cleaned up... But I don't have time for that...

**Comment by rbeucher** [comment]
Once you have a field you can evaluate it's value on any tracers

**Comment by arijitlaik** [comment]
okay. I'll start working on that in july, if there are any of your ideas/guidelines on how it should be done, ill follow them closely

**Comment by rbeucher** [comment]
What is missing here?
